services:
  gameserver:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:443"
    env_file:
      - /home/looperlands/.env
  gameserver_test:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:443"
    env_file:
      - /home/looperlands/.env