services:
  gameserver:
    build: 
      context: .
      dockerfile: Dockerfile.test
      args:
        - "LL_CONFIG_ID=ddns"      
    ports:
      - "8000:443"
    env_file:
      - /home/looperlands/.env