services:
  gameserver:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:443"
    env_file:
      - /home/looperlands/.env
  gameserver_2:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8001:443"
    env_file:
      - /home/looperlands/.env      