name: Push commit
on: [push, workflow_dispatch]
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Commit report
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout prod
          git merge main
          ./config_manager.py configs/prod_config.json
          git commit -am "Automated commit"
          git push

 