name: Prod commit
on: [push, workflow_dispatch]
jobs:
  prod-commit:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: 'prod'

      - name: apply prod config
        run: |
          # do some operation that changes a file in the git repo
          ./config_manager.py configs/prod_config.json
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: commit
        run: |
          # Stage the file, commit and push
          git add .
          git commit -m "prod commit"
          git push origin prod