name: Prod commit
on: [push, workflow_dispatch]
jobs:
  prod-commit:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - uses: actions/checkout@v3
        name: checkout
        with:
          fetch-depth: 0
      - name: Commit
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout prod
          ./config_manager.py configs/prod_config.json
          git commit -am "prod commit" 
          git push

 