name: Push commit
on: [push, workflow_dispatch]
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'prod'
      - name: Create local changes
        run: |
          git merge main
          ./config_manager.py configs/prod_config.json   
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}